---
- name: Playbook to configure VMs/hosts with changes required to be a kubernetes node
  hosts:  nodes
  tasks:
    - name: Adding key and repo
      apt_key:
        url:  "{{ key_url }}"
        state:  present
    - apt_repository:
        repo: "{{ k8_repo }}"
        state: present

    - name: Installing required packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Backup fstab and disable swap
      lineinfile:
        path: /etc/fstab
        regexp: "swap"
        state: absent 
        backup: yes
    - command: "swapoff -a"

    - name: Load kernel modules
      modprobe:
        name: "{{ item }}"
        state:  present
      with_items: "{{ kern_mods }}"

    - name: More kernel modifications
      copy:
        src:  "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items: "{{ kern_config_files }}"
      notify:
        - load settings from system configuration files

    - name: Create containerd config directory and generate config file
      file:
        path: "{{ containerd_config_dir }}"
        state:  directory

    - shell:
        cmd:  "sudo containerd config default>/etc/containerd/config.toml"
      notify:
        - restart containerd

    - name: Enable kubelet
      service:
        name: kubelet
        state:  started
        enabled:  yes
      
  handlers:
    - name: load settings from system configuration files
      shell:
        cmd:  "sysctl --system"

    - name: restart containerd
      service:
        name: containerd
        state: restarted
        enabled:  yes

